First, Walk to 'fridge'
Then, Grab 'handle' of 'fridge'
Then, Pull 'handle' outwards to open
Then, Reach hand forward
Then, Grab 'Peanut Butter Jar'
Then, Turn around
Then, Walk towards 'table'
Then, Place 'Peanut Butter Jar' onto 'table'
Then, Turn around
Then, Walk to 'fridge'
Then, Reach hand forward
Then, Grab 'Grape Jelly Jar'
Then, Turn around
Then, Walk towards 'table'
Then, Place 'Grape Jelly Jar' onto 'table'
Then, Turn around
Then, Walk to 'fridge'
Then, Reach hand forward
Then, Grab 'Loaf of Bread'
Then, Turn around
Then, Walk towards 'table'
Then, Place 'Loaf of Bread' onto 'table'
Then, Walk to 'fridge'
Then, Grab 'handle' of 'fridge'
Then, Pull 'handle' inwards to close
Then, Walk to 'cupboard'
Then, Open 'cupboard'
Then, Grab 'Hand Towel' Roll
Then, Take 1 sheet of 'Hand Towel'
Then, Close 'cupboard'
Then, Turn around
Then, Walk to 'table'
Then, Place 'Hand Towel' sheet onto 'table'
Then, Grab 'Loaf of Bread'
Then, Twist the tie to open
Then, Reach hand into 'Loaf of Bread'
Then, Pull out two slices of 'Bread'
Then, Place slices onto 'Hand Towel' sheet
Then, Turn around
Then, Walk to 'fridge'
Then, Grab 'handle' of 'fridge'
Then, Pull 'handle' outwards to open
Then, Reach hand forward
Then, Place 'Loaf of Bread' into fridge
Then, Grab 'handle' of 'fridge'
Then, Pull 'handle' inwards to close
Then, Turn around
Then, Walk towards 'drawer'
Then, Grab 'handle' of 'drawer'
Then, Pull 'handle' to open 'drawer'
Then, Reach into 'drawer'
Then, Grab a 'knife'
Then, Grab 'handle' of 'drawer'
Then, Push 'handle' to close 'drawer'
Then, Turn Around
Then, Walk to 'table'
Then, Place 'knife' onto 'table'
Then, Open both jars
Then, Grab 'knife'
Then, Place 'knife' into 'Peanut Butter Jar'
Then, Scoop a small amount with 'knife'
Then, Use 'knife' to spread 'Peanut Butter' onto first slice
Then, Place 'knife' into 'Grape Jelly Jar'
Then, Scoop a small amount with 'knife'
Then, Use 'knife' to spread 'Grape Jelly' onto second slice
Then, Place 'knife' onto 'table'
Then, Close both 'jars'
Then, Place first slice onto second slice
Then, Breakdance in success on the 'table' and do a Backflip